server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://47.93.61.140/heima?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: Lj586492
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 47.93.61.140
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.user.pojo